# Generated by Django 3.0.2 on 2020-01-22 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=50, verbose_name='Categorie')),
                ('slug', models.SlugField(help_text='Automatiquement formé à partir du titre.', verbose_name='Référence')),
            ],
            options={
                'verbose_name': 'catégorie',
                'ordering': ('cat',),
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('slug', models.SlugField(help_text='Automatiquement formé à partir du titre.', max_length=100, verbose_name='Url')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='audio/', verbose_name='Image de description')),
                ('url_audio', models.URLField(verbose_name='Url fichier audio')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('categorie', models.ManyToManyField(to='cast.Categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Podcast',
                'ordering': ('publish',),
            },
        ),
    ]
