# Generated by Django 3.0.2 on 2020-01-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='cat',
            field=models.CharField(choices=[('showbiz', 'Showbiz'), ('evenement', 'Evenement'), ('culture', 'Culture'), ('music', 'Music'), ('documentaire', 'Documentaire'), ('formation', 'Formation'), ('interview', 'Interview'), ('reportage', 'Reportage')], default='draft', max_length=50, verbose_name='Categorie'),
        ),
    ]
