# Generated by Django 3.0.2 on 2020-01-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0003_auto_20200122_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ('cat',), 'verbose_name': 'catégorie', 'verbose_name_plural': 'catégories'},
        ),
        migrations.AlterModelOptions(
            name='podcast',
            options={'ordering': ('publish',), 'verbose_name': 'Podcast', 'verbose_name_plural': 'Podcasts'},
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='audio/', verbose_name='Image de description'),
        ),
    ]
