# Generated by Django 3.0.2 on 2020-01-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0004_auto_20200122_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(help_text='Automatiquement formé à partir du titre.', unique=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='slug',
            field=models.SlugField(help_text='Automatiquement formé à partir du titre.', max_length=100, unique=True, verbose_name='Url'),
        ),
    ]
