# Generated by Django 3.0.2 on 2020-01-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0005_auto_20200122_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='image',
        ),
        migrations.AddField(
            model_name='podcast',
            name='large_image',
            field=models.ImageField(blank=True, help_text="Dimension d'image recommandé (720x480).", null=True, upload_to='audio/', verbose_name='Image de description'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='small_image',
            field=models.ImageField(blank=True, help_text="Dimension d'image recommandé (150x150).", null=True, upload_to='audio/', verbose_name='Image de description'),
        ),
    ]
