# Generated by Django 3.0.2 on 2020-01-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0006_auto_20200122_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='large_image',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='small_image',
        ),
        migrations.AddField(
            model_name='podcast',
            name='image',
            field=models.ImageField(blank=True, help_text="Dimension d'image recommandé (300x306).", null=True, upload_to='audio/', verbose_name='Image de description'),
        ),
    ]
