# Generated by Django 3.0.2 on 2020-01-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0007_auto_20200122_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='like',
            field=models.IntegerField(default=1, verbose_name='Nombre de votes'),
        ),
    ]
