# Generated by Django 3.0.2 on 2020-01-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0008_podcast_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Nombre de votes'),
        ),
    ]
